// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compile() {
  return window['go']['main']['App']['Compile']();
}

export function RenderHTML() {
  return window['go']['main']['App']['RenderHTML']();
}
